### ISSUE TITLE
Improve instructions so that the opened issue is closed as soon as possible

### ISSUE THREAD

**Issue by simoneb** [nearform/github-action-notify-release#264]
At the moment the instructions suggest to run the action on a schedule, but when a release is made, what happens is that the issue is not closed until the next execution of the schedule. It would make more sense if the issue was closed as soon as the release is done, which (I believe) basically boils down to adding a trigger in the workflow where this action is used, and wouldn't require any further changes to the source code of the action itself.

This should also reflect in the docs as the recommended way to use the action.

**Comment by simoneb** [comment]
Let's also:

- update our repo template with this change
- bulk update all repos using this action to change the workflow to the new one. you can use https://github.com/lindell/multi-gitter, check with @ilteoood

**Comment by sameer-coder** [comment]
Closing this issue since all nearform repositories with the notify-release workflow have been updated with this change
