### ISSUE TITLE
Add ability to "snooze" the issue

### ISSUE THREAD

**Issue by simoneb** [nearform/github-action-notify-release#280]
- When this action notifies the need to make a release, there is no way to "snooze" it
- Sometimes we may want to skip the release because the changes until then are not relevant enough to do a new release
- The problem with just ignoring the issue is that you will receive no further notifications when the issue is updated to contain additional changes, because the common notifications sent out by github are sent at issue creation, so you end up forgetting about having to do a release

I can see two ways to "snooze" the notification (open to other suggestions):

1. introducing support for closing the issue as "not planned". the action would then need to check if the issue was closed as "not planned" and skip creating a new one, for example by using the date when the issue was closed as the start of the timeframe, similarly to what we use with commit dates already
2. add comments to the issue when it is updated, which would send out a notification

**Comment by marco-ippolito** [comment]
I think the second option is better, it can add a comment with all the commits introduced with the update so it is possible to evaluate whether to release, it acts as a changelog.

**Comment by simoneb** [comment]
If we go with the second option, we need to be careful to avoid spamming. The changelog "feature" it provides is of little value in itself, as the purpose is to know what's going to be released, not how it got at that stage over time. I guess one thing we need to figure out is, how do we know if we should comment or not? I mean, if the commits are the same as those already in the issue, we don't want to comment. Maybe this option is more complicated than the first one :)

**Comment by marco-ippolito** [comment]
everytime a pr is merged into master, the action writes under the notify issue a comment listing the commits from that pr. Do you think it would be too spammy?

**Comment by simoneb** [comment]
Yes. With option one, the idea was to use the close date of the issue (assuming it's available!) as another start day from which to start counting, in the same way as we do with the date of the last commit. basically the (expected) outcome would be to snooze the issue for the same amount of days as `stale-days`

**Comment by simoneb** [comment]
@marco-ippolito yeah thinking about it more it seems that option 1 is simplest and better. It's basically about changing a tiny bit of logic to take whatever is latest between the last release date and the last time the issue was closes as "not planned". Note we'll also need to enhance the body of the issue to explain what happens if you close the issue as not planned

**Comment by marco-ippolito** [comment]
so basically if the issue was closed as "not planned" after the N days of delay it will create another notify issue like the standard one

**Comment by simoneb** [comment]
Yes

**Comment by simoneb** [comment]
Ok I'll try to clarify the requirements since we've been iterating on this for some time and we're still not quite there. 

**Feature request**: when an issue is opened by this action, I want to be able to close it as "not planned" when I don't want to do the release right away but I want to be reminded in the future.

**Current behavior**: if I close the issue, the action will open one again the next time it runs
**Wanted behavior**: if I close the issue, the action will not open another issue for another `stale-days` since the previous issue was closed. I basically want to "snooze" the issue. E.g. remind me in "the future", with "the future" not being user-configurable, but rather postponing the creation of an issue (or the reopening of the closed issue) by `stale-days`.

### Example

The numbers before each item in the list are days

> workflow is configured with `stale-days: 7`, schedule runs daily

- 0: a release is done -> there are no commits pending
- 1..6: nothing happens when the action is run, and nothing would happen even if there were commits because stale-days is 7 (meaning that the action wait 7 days from the last release before opening an issue, if there are newer commits since the release)
- 7: no commits are done -> action is triggered -> no issue is opened (it would be opened if there were new commits since the last release, because stale-days is 7)
- 8: commit abc123 is made (after the daily schedule of the action runs, so nothing happens)
- 9: action runs on schedule -> issue is opened because there are commits
- 10: somebody closes the issue as "not planned", signaling the intention to "snooze" the issue for another `stale-days` **from the moment the issue is closed**
- 11-16: nothing happens because the issue is snoozed, regardless of whether there are new commits or not. basically, the manual close of the issue as "not planned" inhibits any further action, because we have "silenced" it
- 17: when the action runs, the issue is either reopened or a new one created. either way, it should contain ALL commits which were made since the last release

Further things to consider:

- even if the issue is closed, during the snooze time we may still consider keeping it up to date with any possibly newer commits
- what happens if a release is made during the snooze time? I believe we should kill the snooze, meaning close as completed the issue which was closed as unplanned, so that we inhibit the snooze feature

**Comment by simoneb** [comment]
@marco-ippolito I think that given the above extended requirements, you might want to consider starting from scratch because it seems to me that you started with this implementation and although wrong, you didn't change it to reflect any newer understanding that you may have of the issue. Starting from scratch may help coming up with a correct implementation which is not influenced by older code.

**Comment by marco-ippolito** [comment]
At the moment with my PR the action will NOT create a new notify issue if the first one has been closed.
It will create a snooze after stale-day starting from when the latest notify issue was closed and update it every run with pending commits.
If a release is made during snooze time it will kill the snooze I'm 99% sure but I will test it further.

**Comment by simoneb** [comment]
It _will_ create a new issue because there is no logic that prevents the creation of an issue by the existing code. The code you added only creates an issue, it doesn't prevent the existing logic from kicking in.

**Comment by simoneb** [comment]
See this annotated code which hopefully explains what's happening

![image](https://user-images.githubusercontent.com/20181/199333949-afe2050e-3338-4bba-8ebd-5342b68c1dd9.png)

**Comment by marco-ippolito** [comment]
Yes I understand where the mistake is, but it's a easy fix, moving the check if the stale days have passed inside the if condition `if (closedNotifyIssue)` and returning if have not, so the execution will stop
