### ISSUE TITLE
generated Action release body contains unwanted / unexpected contents

### ISSUE THREAD

**Issue by kephail** [nearform/github-action-notify-release#417]
The following is an example of how we expect the issue body to look: https://github.com/nearform/github-action-notify-release/issues/411

this issue following a recent release has some unexpected content: https://github.com/nearform/github-action-notify-release/issues/414

We would like to research where this additional content is coming from.

**Comment by davideroffo** [comment]
> @davideroffo - I am looking into this, any chance you could also take a look?

Hey @kephail , I just created a PR to solve the issue. Please have a look.
